language: python
python:
  - '3.5'
install:
  - pip install -r requirements.txt
script:
  - pytest
after_success:
  - bash <(curl -s https://codecov.io/bash)
env:
  secure: EqOATQj/hXdp137acidDxxDywiGB+c+RE4hYrrb4QNflHlhjqKlp89nGHKvEVqIcE4e4d50LDMXUX3zbfJ8EoutdO3he/JvEZ7gvWyCgM7Z8wd3DkffCw+kba/juJn2/Zfc82bjjW8tvmFU513WXCTpIjeiib/FbgIUj5/iPZfFhYIS8qzwPw/TDdEsjUHPPy3sdilQ+4mLqWxr5cH8U6aaSEDmTodr/Wtp0j/ylqMWzSRzpMMR0J15WSjxVCh4XT++jR6IpLOWCJtq4wu6jEj5R/Eb3Yxqg6qos5iBYPgzwsr6YPlGPQ3wUoLfR8/QJfbEtHRM9ZRg5ZzRPox+4uv82pN5mAdfcCNi5yEoiamRsFDqr/5jokJ0L6W8DMFJfXr0kOK4Od1p44LbspztOxeIpc4EQxCfCIAnKZVaHaykfPmV/4Opiy7x3Zsd2cn+BiocvrYlGzTFGuxq9rCQmtk5V9ik6A0iEc0eUKl42KQRLN5kF67F2XZZN3uYXhTgZZDKFZ3H7NG0gFUtWohZGxG+lMavhy5uW3IDpGnTTHlqhlTgdDXQQNJsZU9L/XH9VMN2rlR+bBh9lpOyA0uDsdO1HLsrHlrP4d2Cj8RUTKWgziwuxnPhA5VyyAhGmas6dkH0BOxcgHe+ZE7MUlUzcgV9EMkXE87s8tTS+/19jxfQ=
